repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      -   id: check-json
      -   id: check-yaml
      -   id: end-of-file-fixer
      -   id: trailing-whitespace
      -   id: detect-private-key
      -   id: requirements-txt-fixer
-   repo: https://github.com/psf/black
    rev: 21.4b2
    hooks:
    -   id: black
        args: [--line-length=160]
-   repo: https://gitlab.com/pycqa/flake8/
    rev: 3.9.1
    hooks:
      -   id: flake8
          args: [--max-line-length=160]
-   repo: local
    hooks:
    -   id: pytest
        name: pytest
        entry: venv/bin/python -m pytest
        language: script
        pass_filenames: false
        # alternatively you could `types: [python]` so it only runs when python files change
        # though tests might be invalidated if you were to say change a data file
        always_run: true
